### ISSUE TITLE
Sax Record Parser 'notprev' -> 'not prev'

### ISSUE THREAD

**Issue by azaroth42** [cheshire3/cheshire3#39]
Traceback (most recent call last):
  File "./run.py", line 67, in <module>
    idx.index_record(session, rec)
  File "../../code/cheshire3/index.py", line 473, in index_record
    processed = self._processRecord(session, rec, src)
  File "../../code/cheshire3/index.py", line 437, in _processRecord
    processed = process.process(session, rawlist)
  File "<string>", line 9, in handler
  File "../../code/cheshire3/extractor.py", line 197, in process_xpathResult
    new = self._mergeHash(new, self.process_node(session, d))
  File "../../code/cheshire3/extractor.py", line 216, in process_node
    sax.saxify(data, handler)
  File "/home/azaroth/install/lib/python2.7/site-packages/lxml-2.3.3-py2.7-linux-x86_64.egg/lxml/sax.py", line 242, in saxify
    return ElementTreeProducer(element_or_tree, content_handler).saxify()
  File "/home/azaroth/install/lib/python2.7/site-packages/lxml-2.3.3-py2.7-linux-x86_64.egg/lxml/sax.py", line 175, in saxify
    self._recursive_saxify(element, {})
  File "/home/azaroth/install/lib/python2.7/site-packages/lxml-2.3.3-py2.7-linux-x86_64.egg/lxml/sax.py", line 221, in _recursive_saxify
    self._recursive_saxify(child, prefixes)
  File "/home/azaroth/install/lib/python2.7/site-packages/lxml-2.3.3-py2.7-linux-x86_64.egg/lxml/sax.py", line 193, in _recursive_saxify
    content_handler.characters(element.tail)
  File "../../code/cheshire3/record.py", line 226, in characters
    prev[0] == "3" and notprev[-1] in [' ', '-']):
NameError: global name 'notprev' is not defined

Should be not prev

**Comment by bloomonkey** [comment]
introduced in df8b281963bf101b9d55c8d7e8f66add38f33c05
