### ISSUE TITLE
errors showed up in the clean-up testing code

### ISSUE THREAD

**Issue by chienyi** [cheshire3/cheshire3#54]
# 

ERROR: test_generate_id (cheshire3.test.testBaseStore.UserPathBdbStoreTestCase)
## Check identifier generation.

Traceback (most recent call last):
  File "/SALT/salt_local/cheshire3/cheshire3/test/testBaseStore.py", line 226, in tearDown
    os.rmdir(defaultPath)
OSError: [Errno 39] Directory not empty: '/nas02/home/c/h/chienyi/.cheshire3-server/testnKhp_1'
# 

ERROR: test_storeDeleteFetch_data (cheshire3.test.testBaseStore.UserPathBdbStoreTestCase)
## Check that data is deleted.

Traceback (most recent call last):
  File "/SALT/salt_local/cheshire3/cheshire3/test/testBaseStore.py", line 226, in tearDown
    os.rmdir(defaultPath)
OSError: [Errno 39] Directory not empty: '/nas02/home/c/h/chienyi/.cheshire3-server/testTG9xQf'
# 

ERROR: test_storeFetch_data (cheshire3.test.testBaseStore.UserPathBdbStoreTestCase)
## Check that data is stored and fetched without corruption.

Traceback (most recent call last):
  File "/SALT/salt_local/cheshire3/cheshire3/test/testBaseStore.py", line 226, in tearDown
    os.rmdir(defaultPath)
OSError: [Errno 39] Directory not empty: '/nas02/home/c/h/chienyi/.cheshire3-server/testrLiQ3a'
# 

ERROR: test_storeFetch_metadata (cheshire3.test.testBaseStore.UserPathBdbStoreTestCase)
## Check that data is stored and fetched without corruption.

Traceback (most recent call last):
  File "/SALT/salt_local/cheshire3/cheshire3/test/testBaseStore.py", line 226, in tearDown
    os.rmdir(defaultPath)
OSError: [Errno 39] Directory not empty: '/nas02/home/c/h/chienyi/.cheshire3-server/testu4GHY0'

---

Ran 556 tests in 23.750s

FAILED (errors=4, skipped=13)

**Comment by bloomonkey** [comment]
I'm unable to reproduce these errors.
Can you list the contents of one of these directories that could not be deleted?
Thanks
