### ISSUE TITLE
Error Loading XML files to Cheshire3

### ISSUE THREAD

**Issue by seekshreyas** [cheshire3/cheshire3#70]
We are getting this error-log when we try loading xml files into our cheshire3 database, even after it says the record has been `loaded`:

<pre>
[2013-07-02 18:33:32] DEBUG: database identifier not specified, discovered: db_ia
[2013-07-02 18:33:32] INFO: Loading documents
[2013-07-02 18:33:32] INFO: Loading: /Users/Shreyas/Documents/_Berkeley/summer/DID/ia-data-extract/extract/000/000/shreyas.xml
[2013-07-02 18:33:32] INFO: Loaded Record
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/Current/bin/cheshire3-load", line 9, in <module>
    load_entry_point('cheshire3==1.0.13', 'console_scripts', 'cheshire3-load')()
  File "/Library/Frameworks/Python.framework/Versions/7.3/lib/python2.7/site-packages/cheshire3-1.0.13-py2.7.egg/cheshire3/commands/cheshire3_load.py", line 47, in main
    wf.process(session, docFac)
  File "<string>", line 26, in handler
  File "/Library/Frameworks/Python.framework/Versions/7.3/lib/python2.7/site-packages/cheshire3-1.0.13-py2.7.egg/cheshire3/database.py", line 198, in commit_indexing
    idx.commit_indexing(session)
  File "/Library/Frameworks/Python.framework/Versions/7.3/lib/python2.7/site-packages/cheshire3-1.0.13-py2.7.egg/cheshire3/index.py", line 548, in commit_indexing
    s.commit_indexing(session, self)
  File "/Library/Frameworks/Python.framework/Versions/7.3/lib/python2.7/site-packages/cheshire3-1.0.13-py2.7.egg/cheshire3/indexStore.py", line 480, in commit_indexing
    raise ConfigFileException(msg)
cheshire3.exceptions.ConfigFileException: <class 'cheshire3.exceptions.ConfigFileException'>: Sort executable for indexStore does not exist
</pre>

As per my configuration, I am using the `master` branch install of this repository not the `developer` branch. 
And my python version

<pre>
$ python --version
Python 2.7.3 -- EPD 7.3-2 (32-bit)
</pre>

@munner17

**Comment by seekshreyas** [comment]
Initially I thought it might be because my XML might not be valid. 

I used a [sample valid xml](http://msdn.microsoft.com/en-us/library/windows/desktop/ms762271%28v=vs.85%29.aspx) which I validated via [W3 Validator](http://validator.w3.org/)

**Comment by bloomonkey** [comment]
The following confirms that the XML was parsed and loaded into the RecordStore

```
[2013-07-02 18:33:32] INFO: Loaded Record
```

The exception you have is

```
Sort executable for indexStore does not exist
```

This means that the unix sort utility executable was not present at the configured location, and could not be found. You appear to be using OSX - I'm not sure where the executable lives on OSX, you might be able to find it using `which sort`.

Where to fix the configuration will depend on how you installed Cheshire3 - what install command did you run?

Incidentally, for work on the Digging Into Data project, you will need to use the `develop` branch rather than `master`. `master` represent the version currently released on PyPI. `develop` contains features for the upcoming release v1.1 including the natural language processing capabilities that are being integrated as part of the project.

**Comment by bloomonkey** [comment]
I should add that removing the dependency on the unix sort utility is on the TODO list as issue #6

**Comment by munners17** [comment]
I currently am having the same issue.  To answer your questions:

My development environment is Ubuntu 12.04 and when i run `which sort`, the response is: /usr/bin/sort

<b>what install command did you run?</b> - I ran all the commands in the <b>Developers</b> section of the Installation area here: https://github.com/cheshire3/cheshire3#installation

Also i'm currently developing in the develop branch.

Please let me know if u need any other information.

**Comment by bloomonkey** [comment]
In your repository clone edit the file `cheshire3/configs/serverConfig.xml` in the `<path type="sortPath">` replace `/bin/sort` with `/usr/bin/sort` (for Ubuntu, the path will be different for OSX).

If you installed as a developer as you say, then you should not need to reinstall.

**Comment by seekshreyas** [comment]
@bloomonkey : Thanks! 
I reinstalled cheshire3 with `virtualenv` (as recommended in the documentation) so as I have a cleaner environment to work in. This time it worked fine without any changes to the config files.
