### ISSUE TITLE
Error in loading

### ISSUE THREAD

**Issue by ReinSi** [cheshire3/cheshire3#74]
I followed the discussion at https://github.com/cheshire3/cheshire3/issues/70, and changed the line <path type="sortPath">/usr/bin/sort</path> in 
cheshire3/configs/serverConfig.xml to /bin/sort (I'm on CentOS). I commented out the original "sortPath" line.

The next load stopped at the same place and generated the following error message: 

rec stored
[2013-12-17 14:22:53] NOTSET: Indexing Record
878 rec created
rec stored
[2013-12-17 14:22:56] NOTSET: Indexing Record
879 rec created
rec stored
[2013-12-17 14:22:59] NOTSET: Indexing Record
0
Traceback (most recent call last):
  File "run.py", line 96, in <module>
    db.commit_indexing(session)
  File "/home/aezros/cheshire3/cheshire3/database.py", line 198, in commit_indexing
    idx.commit_indexing(session)
  File "/home/aezros/cheshire3/cheshire3/index.py", line 552, in commit_indexing
    s.commit_indexing(session, self)
  File "/home/aezros/cheshire3/cheshire3/indexStore.py", line 533, in commit_indexing
    return self.commit_centralIndexing(session, index, sorted)
  File "/home/aezros/cheshire3/cheshire3/indexStore.py", line 776, in commit_centralIndexing
    (termid, recs, occs) = struct.unpack('<lll', val)
struct.error: unpack requires a string argument of length 12

**Comment by bloomonkey** [comment]
I suspect that this is due to a known 64-bit architecture issue; see #73
