### ISSUE TITLE
memory allocation

### ISSUE THREAD

**Issue by ReinSi** [cheshire3/cheshire3#76]
I am running some indexes on my Ubuntu server, and get the following error message complaining about memory allocation. I'm a bit confused as I've run bigger index jobs before on the server and there should be enough space/memory. Anything I've missed? How do I make sure I've got the appropriate memory allocations?

[2014-06-04 15:00:48] INFO: Record 146 stored
[2014-06-04 15:00:48] INFO: Indexing Record
[2014-06-04 15:00:50] INFO: Record 147 created
[2014-06-04 15:00:50] INFO: Record 147 stored
[2014-06-04 15:00:50] INFO: Indexing Record
[2014-06-04 15:00:51] INFO: Finished with 0 errors
Traceback (most recent call last):
  File "run.py", line 101, in <module>
    db.commit_indexing(session)
  File "/usr/local/lib/python2.7/dist-packages/cheshire3/database.py", line 202, in commit_indexing
    idx.commit_indexing(session)
  File "/usr/local/lib/python2.7/dist-packages/cheshire3/index.py", line 563, in commit_indexing
    s.commit_indexing(session, self)
  File "/usr/local/lib/python2.7/dist-packages/cheshire3/indexStore.py", line 520, in commit_indexing
    getShellResult(cmd)
  File "/usr/local/lib/python2.7/dist-packages/cheshire3/utils.py", line 98, in getShellResult
    result = commands.getoutput(cmd)  # causes bug in iRODS
  File "/usr/lib/python2.7/commands.py", line 50, in getoutput
    return getstatusoutput(cmd)[1]
  File "/usr/lib/python2.7/commands.py", line 59, in getstatusoutput
    pipe = os.popen('{ ' + cmd + '; } 2>&1', 'r')
OSError: [Errno 12] Cannot allocate memory

**Comment by bloomonkey** [comment]
This [stackoverflow question](http://stackoverflow.com/questions/1367373/python-subprocess-popen-oserror-errno-12-cannot-allocate-memory) looks at a similar problem.

Combining this, with the assumption that you are running a VM as a guest on some share infrastructure, and your assertion that you have successfully run bigger indexing jobs, I would suspect that some other process (possibly your server application, but possibly another guest on the shared host infrastructure) was consuming a large amount of memory at the time, and this accounts for the unavailability of memory for your indexing job.

As a solution, I think that you have a couple of options:
1. Re-run the job at a time when the shared host infrastructure is likely to be under lower load.
2. Run indexing jobs on separate hardware (e.g. a VM on your desktop) and push the resulting store and index files up to the test/live server when complete.

If taking option 2, be sure to run the indexing job on the same architecture (32 vs 64 bit) to ensure compatibility of the resulting index files.
